### ISSUE TITLE
Pylint failing in Github Actions Workflow

### ISSUE THREAD

**Issue by kronomon** [kronomon/fraser-health-childcare-map#16]
For example: https://github.com/kronomon/fraser-health-childcare-map/actions/runs/5182860938/jobs/9340099737

Github Workflow fails with `AttributeError: module 'sqlalchemy' has no attribute '__all__'` message. 
```
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/astroid/transforms.py", line 61, in _visit_generic
    return [self._visit_generic(child) for child in node]
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/astroid/transforms.py", line 61, in <listcomp>
    return [self._visit_generic(child) for child in node]
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/astroid/transforms.py", line 67, in _visit_generic
    return self._visit(node)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/astroid/transforms.py", line 57, in _visit
    return self._transform(node)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/astroid/transforms.py", line 39, in _transform
    ret = transform_func(node)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/pylint_flask_sqlalchemy/__init__.py", line 23, in transform
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 730, in _get_asts
    ast_per_fileitem[fileitem] = self.get_ast(
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1066, in get_ast
    raise astroid.AstroidBuildingError(
astroid.exceptions.AstroidBuildingError: Building error when trying to create ast representation of module 'ccmap.geocode'
```

However, running the same command locally works:
```
pylint $(git ls-files '*.py') --load-plugins pylint_flask_sqlalchemy pylint_flask
```

**Comment by kronomon** [comment]
It turns out Github Actions downloads SQLAlchemy 2.X instead of 1.4.X which causes the issue.

Fixed with a commit to pin SQLAlchemy 1.4 version: https://github.com/kronomon/fraser-health-childcare-map/commit/42fbf4c8048d72099c84b654180510089a96dfd5

Others have this issue as well: https://stackoverflow.com/questions/75275563/attributeerror-module-sqlalchemy-has-no-attribute-all

---

Verified that locally SQLAlchemy 1.4 is downloaded as per the requirements.txt file but the same file is not used in Github workflows
